name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Verify with Maven
      run: mvn verify
    - name: test and generate code coverage
      run: mvn integration-test cobertura:cobertura
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: 6e3fe2f4-d280-409e-b836-47cb5c7ef589
        file: ./target/site/cobertura
        fail_ci_if_error: true
    - name: Build with Maven
      run: mvn -B package --file pom.xml


